"""Enumerations used by the logistics domain."""

from enum import StrEnum


class InboundShipmentStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    IN_TRANSIT = "IN_TRANSIT"
    DELAYED = "DELAYED"
    ARRIVED = "ARRIVED"
    RECEIVING = "RECEIVING"
    PROCESSED = "PROCESSED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    MISSING = "MISSING"


class DeliveryGroupingPolicy(StrEnum):
    TOGETHER_REQUIRED = "TOGETHER_REQUIRED"
    TOGETHER_PREFERRED = "TOGETHER_PREFERRED"
    INDEPENDENT = "INDEPENDENT"


class DeliveryMethod(StrEnum):
    HOME = "HOME"
    PARCEL_LOCKER = "PARCEL_LOCKER"


class ParcelStatus(StrEnum):
    EXPECTED = "EXPECTED"
    RECEIVED = "RECEIVED"
    SCANNED = "SCANNED"
    SORTED = "SORTED"
    STAGED_FOR_ROUTE = "STAGED_FOR_ROUTE"
    LOADED = "LOADED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED_TO_HOME = "DELIVERED_TO_HOME"
    DELIVERED_TO_LOCKER = "DELIVERED_TO_LOCKER"
    COLLECTED_BY_CUSTOMER = "COLLECTED_BY_CUSTOMER"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    RETURNED_TO_WAREHOUSE = "RETURNED_TO_WAREHOUSE"
    DAMAGE_REVIEW = "DAMAGE_REVIEW"
    RETURNED_TO_SENDER = "RETURNED_TO_SENDER"
    CANCELLED = "CANCELLED"


class DriverStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    OFF_DUTY = "OFF_DUTY"
    UNAVAILABLE = "UNAVAILABLE"


class VehicleType(StrEnum):
    VAN = "VAN"
    CARGO_VAN = "CARGO_VAN"
    ELECTRIC_VAN = "ELECTRIC_VAN"


class VehicleOperationalStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    IN_SERVICE = "IN_SERVICE"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"


class RouteStatus(StrEnum):
    PLANNED = "PLANNED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class FailureType(StrEnum):
    CUSTOMER_ABSENT = "CUSTOMER_ABSENT"
    PARCEL_LOCKER_FULL = "PARCEL_LOCKER_FULL"
    VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN"
    OPERATIONAL_DELAY = "OPERATIONAL_DELAY"
    INVALID_ADDRESS = "INVALID_ADDRESS"
    IMPOSSIBLE_DELIVERY_DEADLINE = "IMPOSSIBLE_DELIVERY_DEADLINE"
    DAMAGED_PARCEL = "DAMAGED_PARCEL"


class CommunicationChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH_NOTIFICATION = "PUSH_NOTIFICATION"


class NotificationDeliveryStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
